Issue #118 - correct user manual
dil-classroom/projet-dilemme pull request #120
Opened 2022-06-10 16:38 UTC by Webblitchy

Close #118

2022-06-10 18:39 UTC, superjeffcplusplus approved these changes

2022-06-12 18:14 UTC, Luhrel requested changes

2022-06-12 18:14 UTC, Luhrel commented on README.md
> +- You cannot create folders named `build` or `template` inside other folders, they will be ignored.
```suggestion
### Limitations
- All folders named `build` or `template`, other than those at the site's root folder, won't be copied during the build process.
```

2022-06-15 13:09 UTC, Luhrel approved these changes

2022-06-15 13:09 UTC, merged