Issue #119 - improve error handling
dil-classroom/projet-dilemme pull request #121
Opened 2022-06-10 16:39 UTC by Webblitchy

Close #119

2022-06-10 18:38 UTC, superjeffcplusplus approved these changes

2022-06-12 18:07 UTC, Luhrel requested changes

2022-06-12 18:07 UTC, Luhrel commented on src/main/java/ch/heigvd/dil/cli_cmds/BuildCmd.java
> +          Files.copy(f.toPath(), Paths.get(siteRoot, "build" + folderPath + "/" + f.getName()));
```suggestion
          Files.copy(f.toPath(), Paths.get(siteRoot, "build" + folderPath + "/" + f.getName()));
          System.out.println("The file `" + f.getName()
                  + "` has only been copied because it is not a valid Markdown page.");
          
```

2022-06-15 13:10 UTC, Luhrel approved these changes

2022-06-15 13:11 UTC, merged