Feat/19/version command
dil-classroom/projet-dilemme pull request #28
Opened 2022-03-30 16:48 UTC by Webblitchy

Close #19

2022-03-31 07:41 UTC, Luhrel requested changes

2022-03-31 07:41 UTC, Luhrel commented on src/main/java/ch/heigvd/dil/Main.java
> +  private static final String VERSION = "0.1.0";
It's a non-sense to store the version in a String. Please create a `Version` class, with `major`, `minor` and `patch` final attributes (with getters and a `toString()`).
Then create a static variable `Version PROJECT = new Version(0, 1, 0)` (fell free to rename the variable). Much more convenient like that (thus we can define multiple versions of different parts of the program.

2022-03-31 07:43 UTC, Luhrel requested changes

2022-03-31 07:43 UTC, Luhrel commented on src/main/java/ch/heigvd/dil/cli_cmds/CleanCmd.java
> +
Why the Clean command is in this PR ?

2022-04-01 09:50 UTC, Luhrel approved these changes

2022-04-06 13:06 UTC, BasileCuneo approved these changes

2022-04-06 13:07 UTC, merged