Issue #26 - Add generic config parser and validator
dil-classroom/projet-dilemme pull request #50
Opened 2022-04-19 10:29 UTC by superjeffcplusplus

Close #26
I implemented a new class `ConfigGenerator` that can create a configuration object of the class passed in constructor.
I added the use of this class in `PageContentSeparator` to generate the `Page.Config` object.

Now we can use this new class to generate the `Site.Config` object.

Note that `ConfigGenerator` uses object mapping to create the object. This technique requires a default constructor in the class to create. For this reason I added a default constructor to `Page` object.

2022-04-19 10:57 UTC, Luhrel requested changes
Why is `testFiles/test-config/site-config-missing-owner.json` empty ?

Otherwise, great job !

2022-04-19 10:57 UTC, Luhrel commented on src/main/java/ch/heigvd/dil/data_structures/Page.java
> +    public Config() {}
I'm against this, because IMO `Page.Config` should always be valid.

To fix this, I would create a `json_mapping/Page` which contains the default constructor and everything you need with a `toPageConfig` method.

2022-04-19 10:57 UTC, Luhrel commented on src/main/java/ch/heigvd/dil/utils/parsers/ConfigGenerator.java
> +      throw new RuntimeException("Error in config");
Is there a reason to catch a `ValidationException` and to throw a `RuntimeException` ?
Why simply not catch the exception ?

+ add the `throws` to the method signature please.

2022-04-19 10:57 UTC, Luhrel commented on src/main/java/ch/heigvd/dil/utils/parsers/ConfigGenerator.java
> +      throw new RuntimeException("Error while creating Page.Config instance.");
Same here

2022-04-19 10:57 UTC, Luhrel commented on src/main/java/ch/heigvd/dil/utils/parsers/ConfigGenerator.java
> +      throw new RuntimeException();
and here

2022-04-19 10:57 UTC, Luhrel commented on src/test/java/ch/heigvd/dil/utils/parsers/PageContentSeparatorTest.java
> +      throw new RuntimeException();
(same here in the tests)

2022-04-19 11:03 UTC, superjeffcplusplus commented on src/main/java/ch/heigvd/dil/utils/parsers/ConfigGenerator.java
> +      throw new RuntimeException("Error in config");
Why not but now the goal is to have something working as soon as possible ... so I propose to fix it later

2022-04-19 11:05 UTC, superjeffcplusplus commented on src/main/java/ch/heigvd/dil/utils/parsers/ConfigGenerator.java
> +      throw new RuntimeException("Error in config");
I think that error handling should be a separate issue

2022-04-19 11:07 UTC, superjeffcplusplus commented on src/main/java/ch/heigvd/dil/data_structures/Page.java
> +    public Config() {}
Why not but now the goal is to have something working as soon as possible ... so I propose to fix it lat

2022-04-19 17:49 UTC, superjeffcplusplus commented on src/main/java/ch/heigvd/dil/utils/parsers/ConfigGenerator.java
> +      throw new RuntimeException("Error in config");
I removed the println but kept the retthrow of Runtime, because this error should not occur. But if there is an error, I just want everything to stop.

2022-04-19 17:49 UTC, superjeffcplusplus commented on src/main/java/ch/heigvd/dil/utils/parsers/ConfigGenerator.java
> +      throw new RuntimeException("Error while creating Page.Config instance.");
same comment as above

2022-04-27 12:55 UTC, Webblitchy approved these changes

2022-04-27 13:08 UTC, Luhrel approved these changes
Approved after a long discussion.

2022-04-27 14:30 UTC, merged