Feat/52/add build command
dil-classroom/projet-dilemme pull request #54
Opened 2022-04-27 20:58 UTC by Webblitchy

Close #52

2022-05-03 15:22 UTC, Luhrel requested changes

2022-05-03 15:22 UTC, Luhrel commented on src/main/java/ch/heigvd/dil/utils/FileHandler.java
> +      return null;
Just throw it !

2022-05-03 17:52 UTC, Luhrel requested changes

2022-05-03 17:52 UTC, Luhrel commented on src/main/java/ch/heigvd/dil/cli_cmds/BuildCmd.java
> +    buildDir.mkdir();
What if it fails ?

2022-05-03 17:52 UTC, Luhrel commented on src/main/java/ch/heigvd/dil/cli_cmds/BuildCmd.java
> +    for (File f : new File(path, folderPath).listFiles()) {
What if the `new FIle(...)` fails ?

2022-05-04 13:23 UTC, BasileCuneo approved these changes
seems good

2022-05-04 13:25 UTC, Luhrel approved these changes

2022-05-04 13:25 UTC, merged