Feat/84/implement serve command
dil-classroom/projet-dilemme pull request #88
Opened 2022-05-25 15:07 UTC by superjeffcplusplus

2022-05-28 15:10 UTC, Luhrel requested changes

2022-05-28 15:10 UTC, Luhrel commented on src/main/java/ch/heigvd/dil/Main.java
> +    }
Please add a comment why the if statement is necessary.

2022-05-31 08:41 UTC, Webblitchy approved these changes

2022-05-31 08:45 UTC, Luhrel approved these changes

2022-05-31 08:45 UTC, merged